# gradle properties
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.parallel.only-on-demand=true

# mod properties
mod_archives_base_name=litematica-printer
mod_description=Litematica Printer multi version pack
mod_homepage=https://space.bilibili.com/514411062
mod_id=litematica-printer
mod_wrapper_id=litematica-printer-wrapper
mod_license=AGPL-3.0
mod_maven_group=com.blinkwhite.litematica-printer
mod_name=Litematica Printer
mod_sources=https://github.com/BiliXWhite/litematica-printer
mod_version=1.3-beta.4

## loader & libraries properties
loader_version=0.19.3
pinyin_version=2.5.1
# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok_version=1.18.42

# conditional-mixin-fabric 被 QuickShulker >=1.20.6 依赖
conditional_mixin_version=0.6.4
