pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net'
        }
    }
}

['26.1.2', '26.2', '26.3'].each { version ->
    include(":${version}")
    project(":${version}").with {
        projectDir = file("versions/${version}")
        buildFileName = '../../build.fabric.gradle'
    }
}

include ':1.21.1'
project(':1.21.1').projectDir = file('versions/1.21.1')

include ':core'
