minecraft_dependency=>=26.1 <=26.1.2
minecraft_version=26.1.2

# https://fabricmc.net/develop/
fabric_version=0.152.1+26.1.2

# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/malilib
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib
malilib=malilib-fabric-26.1.2:0.28.6
malilib_dependency=0.28.6
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/litematica
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica
litematica=litematica-fabric-26.1.2:0.27.9
litematica_dependency=0.27.9
# https://modrinth.com/mod/tweakeroo
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo
tweakeroo=tweakeroo-fabric-26.1.2:0.28.4
tweakeroo_dependency=0.28.4

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.5/quickshulker-v3.2.5-mc26.1.2-a7aa281-release.jar

# https://modrinth.com/mod/chest-tracker-port/versions
# https://modrinth.com/mod/where-is-it-port/versions
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://github.com/ponuing/JackFredLib/packages/2707359
# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=18.0.0-alpha.8