minecraft_dependency=>=26.1 <=26.1.2
minecraft_version=26.1.2
java_version=25

# https://fabricmc.net/develop/
fabric_version=0.152.1+26.1.2

# https://modrinth.com/mod/malilib
malilib_dependency=0.28.8
# https://modrinth.com/mod/litematica
litematica_dependency=0.27.9
chainvein=https://github.com/water2004/ChainVeinFabric/releases/download/v3.0.0/ChainVeinFabric-3.0.0-26.1.jar
chainvein_gametest=https://github.com/water2004/ChainVeinFabric/releases/download/v4.1.0-alpha.3/ChainVeinFabric-4.1.0-alpha.3-26.1.jar
quickshulker=https://github.com/water2004/quickshulker/releases/download/4.0.0-26.1/quickshulker-4.0.0-26.1.jar
quickshulker_legacy=https://github.com/water2004/quickshulker/releases/download/3.0.4/quickshulker-3.0.4-26.1.jar
bedrock_miner_gametest=https://github.com/bunnyi116/fabric-bedrock-miner/releases/download/v1.6.1/bedrock-miner-v1.6.1-mc26.1.jar
block_miner_gametest=https://github.com/z7087/blockminer/releases/download/prerelease/blockminer-v1.1.1-mc26.1.2.jar
fabric_bedrock_miner_gametest=https://cdn.modrinth.com/data/BYMHqMXz/versions/dd2fy7eP/bedrock-miner-2.0.11%2B26.1.2.jar

# https://modrinth.com/mod/chest-tracker-port/versions
# https://modrinth.com/mod/where-is-it-port/versions
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://github.com/ponuing/JackFredLib/packages/2707359
# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=18.0.0-alpha.8
