minecraft_dependency=>=1.21.2 <=1.21.3
minecraft_version=1.21.3

# https://fabricmc.net/develop/
fabric_version=0.106.1+1.21.3

# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/malilib
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib
malilib=malilib-fabric-1.21.3:0.22.8
malilib_dependency=0.22.8
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/litematica
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica
litematica=litematica-fabric-1.21.3:0.20.9
litematica_dependency=0.20.9
# https://modrinth.com/mod/tweakeroo
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo
tweakeroo=tweakeroo-fabric-1.21.3:0.22.8
tweakeroo_dependency=0.22.8

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.2.3-1.21.3/quickshulker-2.2.3-1.21.3.jar

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://modrinth.com/mod/modmenu/versions
modmenu=12.0.0