minecraft_dependency=>=26.2 <=26.3
minecraft_version=26.2
java_version=25

# https://fabricmc.net/develop/
fabric_version=0.152.1+26.2

# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/malilib
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib
malilib=malilib-fabric-26.2:0.29.2
malilib_dependency=0.29.2
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/litematica
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica
litematica=litematica-fabric-26.2:0.28.3
litematica_dependency=0.28.3
chainvein=https://github.com/water2004/ChainVeinFabric/releases/download/v3.0.0/ChainVeinFabric-3.0.0-26.2.jar
quickshulker=https://github.com/water2004/quickshulker/releases/download/4.0.0/quickshulker-4.0.0-26.2.jar
quickshulker_legacy=https://github.com/water2004/quickshulker/releases/download/3.0.4/quickshulker-3.0.4-26.2.jar

# https://modrinth.com/mod/chest-tracker-port/versions
# https://modrinth.com/mod/where-is-it-port/versions
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://github.com/ponuing/JackFredLib/packages/2707359
# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=20.0.1
