minecraft_dependency=>=26.2 <=26.3
minecraft_version=26.2

# https://fabricmc.net/develop/
fabric_version=0.152.1+26.2

# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/malilib
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib
malilib=malilib-fabric-26.2:0.29.2
malilib_dependency=0.29.2
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/litematica
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica
litematica=litematica-fabric-26.2:0.28.3
litematica_dependency=0.28.3
# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo
tweakeroo=tweakeroo-fabric-26.2:0.29.2
tweakeroo_dependency=0.29.2

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.5/quickshulker-v3.2.5-mc26.2-a7aa281-release.jar

# https://modrinth.com/mod/chest-tracker-port/versions
# https://modrinth.com/mod/where-is-it-port/versions
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://github.com/ponuing/JackFredLib/packages/2707359
# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=20.0.0-beta.2