minecraft_dependency=1.21.5
minecraft_version=1.21.5

# https://fabricmc.net/develop/
fabric_version=0.121.0+1.21.5

# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/malilib
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib
malilib=malilib-fabric-1.21.5:0.24.3
malilib_dependency=0.24.3
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/litematica
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica
litematica=litematica-fabric-1.21.5:0.22.5
litematica_dependency=0.22.5
# https://modrinth.com/mod/tweakeroo
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo
tweakeroo=tweakeroo-fabric-1.21.5:0.24.3
tweakeroo_dependency=0.24.3

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.4.3-1.21.5/quickshulker-2.4.3-1.21.5.jar

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://modrinth.com/mod/modmenu/versions
modmenu=14.0.1
