plugins {
    id 'java-library'
}

group = 'com.blinkwhite.litematica-printer'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll('-Xlint:deprecation', '-Xlint:unchecked')
}
