minecraft_dependency=>=26.3 <=26.3
minecraft_version=26.3
java_version=25
loader_version=0.19.5

# https://fabricmc.net/develop/
fabric_version=0.160.6+26.3

# https://modrinth.com/mod/malilib
malilib_dependency=0.30.1
# https://modrinth.com/mod/litematica
litematica_dependency=0.29.0
chainvein=https://github.com/water2004/ChainVeinFabric/releases/download/v4.1.0/ChainVeinFabric-4.1.0+26.3.jar
chainvein_gametest=https://github.com/water2004/ChainVeinFabric/releases/download/v4.1.0/ChainVeinFabric-4.1.0+26.3.jar
quickshulker=https://github.com/water2004/quickshulker/releases/download/4.0.1%2B26.3/quickshulker-4.0.1+26.3.jar
quickshulker_legacy=https://github.com/MoRanpcy/quickshulker/releases/download/3.1.0-26.3/quickshulker-3.1.0-26.3.jar
network_chaos=https://github.com/water2004/NetworkChaosFabric/releases/download/1.0.0-alpha.3%2B26.3/network-chaos-fabric-1.0.0-alpha.3%2B26.3.jar
bedrock_miner_gametest=
block_miner_gametest=https://github.com/z7087/blockminer/releases/download/prerelease/blockminer-v1.1.1-mc26.3.jar
fabric_bedrock_miner_gametest=https://cdn.modrinth.com/data/BYMHqMXz/versions/17tTXxy5/bedrock-miner-2.0.11%2B26.3.jar

# https://modrinth.com/mod/chest-tracker-port/versions
# https://modrinth.com/mod/where-is-it-port/versions
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://github.com/ponuing/JackFredLib/packages/2707359
# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=21.0.0-alpha.1
