minecraft_dependency=>=1.21 <=1.21.1
minecraft_version=1.21.1

#https://fabricmc.net/develop/
fabric_version=0.116.8+1.21.1

# https://modrinth.com/mod/malilib
# https://jitpack.io/#sakura-ryoko/malilib
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/malilib
malilib=malilib-fabric-1.21:0.21.10
malilib_dependency=0.21.10
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/litematica
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/litematica
litematica=litematica-fabric-1.21:0.19.61
litematica_dependency=0.19.61
# https://modrinth.com/mod/tweakeroo
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://masa.dy.fi/maven/sakura-ryoko/fi/dy/masa/tweakeroo
tweakeroo=tweakeroo-fabric-1.21:0.21.61
tweakeroo_dependency=0.21.61

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.0.3-1.21.1/quickshulker-2.0.3-1.21.1.jar

# https://modrinth.com/mod/chest-tracker/versions
# https://modrinth.com/mod/where-is-it/versions?l=fabric
# https://maven.jackf.red/#/releases/red/jackf/jackfredlib/jackfredlib
# https://modrinth.com/mod/modmenu/versions
modmenu=11.0.3
