name: build
on:
  push:
    branches: [main]
    paths-ignore: ['*.md']
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'SKIP') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup jdk
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache Gradle dependencies
        id: gradle-cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle
            ./libs
          key: ${{ runner.os }}-gradle-common
          restore-keys: |
            ${{ runner.os }}-gradle-common

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # If `step: gradle-cache` fails to cache, start downloading dependencies to reduce build failures
      - name: Download dependencies
        if: |
          steps.gradle-cache.outputs.cache-hit != 'true' ||
          contains(github.event.head_commit.message, 'DEPS')
        run: ./gradlew dependencies --stacktrace

      - name: Build version projects
        run: ./gradlew build

      - name: Capture version artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: versions/*/build/libs/*.jar
