name: release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: Git tag to attach build artifacts to
        type: string
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      IS_THIS_RELEASE: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache Gradle dependencies
        id: gradle-cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle
            ./libs
          key: ${{ runner.os }}-gradle-common
          restore-keys: |
            ${{ runner.os }}-gradle-common

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # If `step: gradle-cache` fails to cache, start downloading dependencies to reduce build failures
      - name: Download dependencies
        if: steps.gradle-cache.outputs.cache-hit != 'true'
        run: ./gradlew dependencies --stacktrace

      - name: Build fabricWrapper subprojects
        run: |
          chmod +x gradlew
          ./gradlew :fabricWrapper:build --stacktrace

      - name: Capture versionpack artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: fabricWrapper/build/libs/*.jar
          archive: false

      - name: Collect mod jars
        run: |
          shopt -s extglob
          mkdir mod-jars
          for jar in fabricWrapper/build/libs/!(*-@(dev|sources|shadow)).jar; do
              cp -p "$jar" mod-jars/
          done
          ls -l mod-jars

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.target_release_tag || github.ref_name }}
          files: mod-jars/*
          token: ${{ secrets.GITHUB_TOKEN }}
